### ISSUE TITLE
Added slug along with the name for better understanding

### ISSUE THREAD

**Issue by fallacy321** [sdelements/lets-chat#382]
For displaying the list at the tab, it would be better to display slug along with name as shown in the attached screenshot

Here is my commit for the same: 
https://github.com/fallacy321/lets-chat/commit/ea14cd6f3d361a14e6b4b75cd4149fde064fa087

![slug](https://cloud.githubusercontent.com/assets/3140219/6868982/3c0a7636-d4b6-11e4-8ca5-d87ee441fde5.png)

**Comment by geoffwhittington** [comment]
This change is probably useful in the context of your data but it doesn't work for everyone. For our deployment we have slugs that look like "54bff621a1e1aedf3ccd41e4".

My suggestion is that if your room names don't have enough information - update your room names. What do your room names/slugs mean?

**Comment by fallacy321** [comment]
Hi @geoffwhittington 

Isnt 54bff621a1e1aedf3ccd41e4 is perhaps the slug id {{id}} . I instead of displaying just name, displayed it like - {{name}} at {{slug}} and not {{name}} at {{id}} 
What do you mean by not enough information? As slug is a required field on add a room I think ? 

Regards

**Comment by geoffwhittington** [comment]
@fallacy321 You're right, slugs could have more information - ours happen to be id's.

What do you make your room and slug entry fields mean? You propose to concatenate room and slug with " at " - which implies that your data actually makes sense with " at ". The front-end makes no assumption about the two fields. Room title is a title, and Slug is some unique identifier for the room. 

For example, someone could enter Room="Testing" and slug="the-testing-room". With this code change it would render as "Testing at the-testing-room", which doesn't make sense to me.

**Comment by fallacy321** [comment]
@geoffwhittington Hi, I meant name and slug as the fields one provides while adding a room. so wont <name> at <slug> be useful?

**Comment by necramirez** [comment]
The term slug came from newspaper publishing:
http://en.m.wikipedia.org/wiki/Slug_(publishing) -- being a short name it
clearly meant it wasn't really used side-by-side with the actual title, but
only as a substitute.

In web publishing (see Slug section,
http://en.m.wikipedia.org/wiki/Slug_(web_publishing) ), it generally became
a URL-friendly form of a title, stripping punctuations, common articles and
converting spaces into dashes.

As in Geoff's example, where a room named Testing can have a slug
"the-testing-room", a more "real" example might be a room named
"Asia-Pacific Team" which could then have the slug "ap_team". This would
make it easier for the message parser to detect mentions of the room in
messages by way of hash-tag, i.e. "#ap_team", because of the limited type
of characters used (no spaces).

IMO, the slug field should be used for this very purpose, despite being
possible to be used to contain extra information.

**Comment by sibartlett** [comment]
@fallacy321 yep, @necramirez's explanation above is correct.

A slug is a short URL friendly version of the room's name.

We currently use it in hashtags and XMPP. In the future, we may also change the web-client to use slug in the URL instead of ID.

**Comment by fallacy321** [comment]
Great ! @sibartlett Thank you for the information @necramirez  :)
