### ISSUE TITLE
change app domain from / to /letschat

### ISSUE THREAD

**Issue by vosgaust** [sdelements/lets-chat#411]
Hi, I'm wondering if it is possible to have the application working at http:www.somedomain.com/letschat instead of the root directory.

I'm using apache with a poxy pass but the application keeps trying to find the files at root. I've had a look to configuration files but I haven't seen anything related to this.

**Comment by sibartlett** [comment]
@vosgaust can you try the latest code on the master branch?

**Comment by g0dkar** [comment]
I'm trying to do the same, with the lastest code from master branch (just installed yesterday) - I was wondering how we could change that... Is there a configuration or anything?

**Comment by sibartlett** [comment]
@g0dkar no, we've been recommending to proxy the Let's Chat using nginx.

**Comment by g0dkar** [comment]
And I've done that, like this:

```
location /chat { ... proxy_pass http://localhost:5000/; ... }
```

But when I access http://localhost/chat I get redirected to /login (which I think it should be /chat/login)

**Comment by snorpey** [comment]
i ran into the the same issue. @g0dkar were you able to fix the issue somehow?

**Comment by dudleyperkins** [comment]
I would be interested in a solution too.

I only had the redirect-to-/login-problem, without using a trailing slash in Proxypass/Reverse.

Now that i've added this i'm not redirected anymore, but also don't see the login page - only the Error "Cannot GET"!?

**Comment by dudleyperkins** [comment]
mmh, i have the suspicion the problem is really just the hardcoded(?) redirect to /login, if i call /chat/login directly it's working just fine.

These are the configurations i tested and so far everything works as expected.

Apache:
ProxyRequests off
ProxyPass /chat/ http://127.0.0.1:5000/
ProxyPassReverse /chat/ http://127.0.0.1:5000/
Redirect "/login" "/chat/login"

Nginx:
location /chat/ {
                proxy_pass http://127.0.0.1:5000/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
        location = /login {
                return 301 /chat/login;
        }

But in a future release it would be cool if lets-chat would redirect relatively to {URL}/login. The problem with the redirect in the Web-Server is that you could not use the path /login for anything else because you're always beeing redirected to lets-chat.

Not a big problem, but in my case i integrated lets-chat on a gateway-server that serves many different web-services.

**Comment by dudleyperkins** [comment]
okay one more before leaving to the weekend, another redirect is needed:

Redirect "/media" "/chat/media"

or

location = /media {
return 301 /chat/media;
}

**Comment by lukepfarrar** [comment]
Also:
`Redirect "/files" "/chat/files"`
or

```
location = /files {
return 301 /chat/files;
}
```
