### ISSUE TITLE
Moving away from jQuery

### ISSUE THREAD

**Issue by warent** [sdelements/lets-chat#648]
Howdy everyone,

So this project definitely needs to move away from jQuery. Can I ask what the reasoning is behind using React/Redux vs. Angular? Angular is not only far more matured, but many more people are familiar with Angular, it's less experimental, and it can still do nearly everything React can do--in different ways. Benchmarking proves Angular is as fast as React. Also, Angular 3 is being released soon.

This is definitely a project I would like to work on, but if the team is going to push bleeding-edge technologies like this for no clear reason then I cannot assist further.

**Comment by hhaidar** [comment]
Hey @warent ,

Thank you for the input, I appreciate you taking the time and effort :)

We're going with React mainly due to the facile learning curve, minimal assumptions, and current popularity. While Angular 2.0 looks really nice, I've only worked with Angular 1.x and didn't feel comfortable after going through headaches with directives/scope/terminology/etc. Angular's mission is to provide a complete framework and React is more laissez-faire. At the end of the day they're both great tools, but the most important thing is what you create with them.

I'm currently working on a new React/Redux based client. It's still very early in development (just enough to open a room and write/receive messages). I'll have some time this holiday break and hopefully can coax my coworkers to help out. Current goal is to get parity with the client in master.

Please feel free to take a look: #653
