### ISSUE TITLE
package.json Credits -- Suggestion

### ISSUE THREAD

**Issue by warent** [sdelements/lets-chat#651]
Hi,

I suggest we only point to a singular company as the author of lets-chat, given that this is about building a legitimate product, and not to stroke our egos. If someone is interested in seeing who the developers are that maintain the project they will check the git repo.

Agreed?

**Comment by funkaoshi** [comment]
Disagree!

There are a pool of developers working on the product in their spare time, here at Security Compass, and since it's become more popular as an open source tool other people have sent us their contributions. It's a nice nod to everyone's effort to be included in the authors list. I would think making @hhaidar or Security Compass the author would be more about ego stroking.

Thanks for the feedback.
